# Generated by Django 4.0.3 on 2022-03-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewt', '0002_customuser_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='manuData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_uid', models.CharField(max_length=4)),
                ('ram_uid', models.CharField(max_length=4)),
                ('hdd_uid', models.CharField(max_length=4)),
                ('ssd_uid', models.CharField(max_length=4)),
                ('processor_uid', models.CharField(max_length=4)),
                ('graphics_uid', models.CharField(max_length=4)),
                ('battery_uid', models.CharField(max_length=4)),
            ],
        ),
    ]
