# Generated by Django 4.0.3 on 2022-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewt', '0003_manudata'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_uid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid_list', models.JSONField()),
            ],
        ),
    ]
