# Generated by Django 4.0.3 on 2022-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewt', '0004_save_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_uid',
            name='username',
            field=models.CharField(default='abcd', max_length=100),
        ),
    ]
