# Generated by Django 4.0.3 on 2022-03-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewt', '0005_save_uid_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_uid',
            name='category',
            field=models.CharField(default='Manufacturer', max_length=100),
        ),
    ]
