# Generated by Django 4.0.3 on 2022-03-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewt', '0006_save_uid_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_uid',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
