# Generated by Django 4.0.3 on 2022-03-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewt', '0008_alter_save_uid_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(max_length=100)),
                ('sender_category', models.CharField(max_length=100)),
                ('uid', models.JSONField()),
                ('receiver_username', models.CharField(max_length=100)),
                ('receiver_category', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
