# Generated by Django 4.0.3 on 2022-03-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewt', '0010_uid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uid_status',
            name='modified',
            field=models.BooleanField(default=False),
        ),
    ]
